services: # 定義服務
    app: # 定義名為 app 的服務
        build: . # 從當前目錄構建 Docker 映像
        container_name: laravel_app # 設定容器名稱為 laravel_app
        restart: always # 設定容器總是重新啟動
        working_dir: /var/www # 設定工作目錄為 /var/www
        volumes: # 定義掛載卷
            - .:/var/www # 將當前目錄掛載到容器的 /var/www
        networks: # 定義網路
            - laravel # 使用名為 laravel 的網路
        depends_on: # 定義依賴服務
            - db # 依賴 db 服務
        env_file: # 定義環境變數檔案
            - .env # 使用 .env 檔案

    web: # 定義名為 web 的服務
        image: nginx:latest # 使用最新版本的 nginx 映像
        container_name: nginx # 設定容器名稱為 nginx
        restart: always # 設定容器總是重新啟動
        ports: # 定義端口映射
            - "8000:80" # 將主機的 8000 端口映射到容器的 80 端口
        volumes: # 定義掛載卷
            - .:/var/www # 將當前目錄掛載到容器的 /var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # 將 nginx 配置檔案掛載到容器的指定位置
        networks: # 定義網路
            - laravel # 使用名為 laravel 的網路
        depends_on: # 定義依賴服務
            - app # 依賴 app 服務

    db: # 定義名為 db 的服務
        image: mysql:8.0 # 使用 8.0 版本的 mysql 映像
        container_name: mysql_db # 設定容器名稱為 mysql_db
        restart: always # 設定容器總是重新啟動
        env_file: # 定義環境變數檔案
            - .env # 使用 .env 檔案
        environment: # 定義環境變數
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # 設定 MySQL root 密碼
            MYSQL_DATABASE: ${DB_DATABASE} # 設定 MySQL 資料庫名稱
            MYSQL_USER: ${DB_USERNAME} # 設定 MySQL 使用者名稱
            MYSQL_PASSWORD: ${DB_PASSWORD} # 設定 MySQL 使用者密碼
        ports: # 定義端口映射
            - "3306:3306" # 將主機的 3306 端口映射到容器的 3306 端口
        networks: # 定義網路
            - laravel # 使用名為 laravel 的網路

    phpmyadmin: # 定義名為 phpmyadmin 的服務
        image: phpmyadmin:latest # 使用最新版本的 phpmyadmin 映像
        container_name: phpmyadmin # 設定容器名稱為 phpmyadmin
        restart: always # 設定容器總是重新啟動
        depends_on: # 定義依賴服務
            - db # 依賴 db 服務
        environment: # 定義環境變數
            PMA_HOST: db # 設定 phpMyAdmin 連接的主機為 db
            PMA_USER: ${DB_USERNAME} # 設定 phpMyAdmin 使用者名稱
            PMA_PASSWORD: ${DB_PASSWORD} # 設定 phpMyAdmin 使用者密碼
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # 設定 MySQL root 密碼
        ports: # 定義端口映射
            - "9000:80" # 將主機的 8080 端口映射到容器的 80 端口
        networks: # 定義網路
            - laravel # 使用名為 laravel 的網路

networks: # 定義網路
    laravel: # 定義名為 laravel 的網路
        driver: bridge # 使用 bridge 驅動
